### PR TITLE
Add flag for `--no-execution` to disable tx exec

### PR DESCRIPTION
**Pull request by tuommaki**
This change allows running a full node that doesn't execute transactions.

Transaction execution is disabled by decoupling event-based transaction handling from the execution backend by introducing an intermediary trait in the `txvalidation` module.

When `--no-execution` flag is specified, nothing from execution backend is started (no scheduler, no provider and no support functionality related to them). Instead, a database backend implementation for that intermediary trait is implemented and once the transaction is fully validated and assets downloaded, it's only saved in the databased and then dismissed.

### CODE REVIEW

**Comment by tuommaki** [comment]
This is a draft for now. I'll test this a little bit later once I have built basic terraform setup for this. Ready for review however.

**Review by musitdev — COMMENTED** [review]
I think you can do it differently. Tx vlaidation, Tx exec and Storage are 3 separate domains. You need only the Tx validation and Storage. So the other possibility is to remove the Tx execution.
To do that, you use directly the: 
`txvalidation::TxEventSender::<txvalidation::TxResultSender>::build(tx_sender.clone())`
in an async loop to get the Tx from it and store them in the database.
This way you skip the execution, you don't start it and more important you don't have to modify it because of a more general need.
Execution layer don't have to know that want to execute a full archive node.

In this model, we skip the mempool because it's too linked to the Execution layer and do nothing, just keep Tx until the scheduler get them.
The better way is to define a mempool that get validated Tx, propagate them if needed (tx propagation is part of the mempool domain) and make them available to the other domain: Tx execution / Storage / ... using stream.

This way you can activate Tx execution, Storage or not depending on the global needs. Each layer don't have to know how they are used.

**Comment by tuommaki** [comment]
>I think you can do it differently. Tx vlaidation, Tx exec and Storage are 3 separate domains. You need only the Tx validation and Storage. So the other possibility is to remove the Tx execution.
>To do that, you use directly the:
`txvalidation::TxEventSender::<txvalidation::TxResultSender>::build(tx_sender.clone())`
in an async loop to get the Tx from it and store them in the database.

Where would I use that?

> This way you skip the execution, you don't start it and more important you don't have to modify it because of a more general need.
> Execution layer don't have to know that want to execute a full archive node.
>
> In this model, we skip the mempool because it's too linked to the Execution layer and do nothing, just keep Tx until the scheduler get them.

If mempool is skipped, how does the transaction gets persisted?

> The better way is to define a mempool that get validated Tx, propagate them if needed (tx propagation is part of the mempool domain) and make them available to the other domain: Tx execution / Storage / ... using stream.
>
> This way you can activate Tx execution, Storage or not depending on the global needs. Each layer don't have to know how they are used.

I don't fully understand your suggestion at concrete level, but it sounds like you'd have a simpler / better solution than I have. Can you elaborate a bit so I can get on the same page :slightly_smiling_face:

**Comment by tuommaki** [comment]
This second revision should be now pretty much the same change that you suggested in your PR.

**Review by musitdev — APPROVED** [review]

**Pull request merged**
